language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - PATH="$HOME/.cargo/bin:$PATH" cargo install --verbose rustfmt

script:
  - ./scripts/travis_test.sh
