[package]
name = "mongo_oplog"
version = "0.0.1"
authors = ["Gabriel Castro <dev@GabrielCastro.ca>"]
exclude = [".travis.yml"]

[dependencies]
mongo_driver = "0.4.*"
bson = "0.3.*"
log = "0.3.*"
regex = "0.1"

[dev-dependencies]
env_logger = "0.3.*"
